### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by joyswing** [dishait/tov-template#1]
请问i18n怎么支持？

**Comment by markthree** [comment]
你好，这需要插件 [vue-i18n-next](https://github.com/intlify/vue-i18n-next)，不过繁杂的配置或许会使你感到困惑，所以我想在下一个版本中内置支持。

**Comment by markthree** [comment]
靓仔你好，i18n 已经得到内置的支持，可见[tov-template/i18n 国际化支持](https://github.com/dishait/tov-template#23-i18n-%E5%9B%BD%E9%99%85%E5%8C%96%E6%94%AF%E6%8C%81)

**Comment by joyswing** [comment]
太棒了！
