### ISSUE TITLE
管理后台框架例子

### ISSUE THREAD

**Issue by 1185497683** [dishait/tov-template#10]
一般管理后台框架，有个Header,Body,Footer,以及常用的菜单，是用tailwindcss来构建好，还是用ElementPlus好，大神你这边用的是啥样的，能够给个简单的例子。

**Comment by markthree** [comment]
靓仔你好，目前内部已经在基于该模板进行上层的开发了，最简单的方式仍然是使用现有的组件库。当然也有其他靓仔开始有在做后台了，至于组件库的选型可见该讨论 👉 [ui框架推荐](https://gitee.com/dishait/tov-template/issues/I4VEXU#note_8910860)。

**Comment by markthree** [comment]
至于例子，目前是没有一个简洁的，后续可能会在内部开发中沉淀出来一些内部后台开发过程中的例子以及好用的工具等等

**Comment by markthree** [comment]
副本 #17
