### ISSUE TITLE
page 二级目录指定layout后，同时也加载一级目录下的layout

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#100]
## 信息
page 二级目录指定layout后，同时也加载一级目录下的layout

一级目录底部放有 首页、消息、订单、我的
首页点击商品跳转到 二级目录下 商品详情页，此页面指定了新的layout，不应该有底部的导航了，但是现在两个layout都加载了。

### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@luoqiz 靓仔，我认为这是一个正常行为。因为 [vite-plugin-vue-meta-layouts](https://github.com/dishait/vite-plugin-vue-meta-layouts) 布局系统的原理就是将设置的 `layout` 作为 `父路由`，所以上边的场景其实是套了两层 `layout`。

当然你可以这样

```html
<!-- pages/一级/二级.vue -->
<route lang="json">
{
  "meta": {
   "layout": "二级布局",
   "disbaleTabbar": true,
  }
}
</route>
``` 

然后在你的 `一级布局` 里进行判断是否要 `tabar` 

```html
<!-- layout/一级布局.vue --->
<script setup lang="ts">
import { useRoute } from "vue-router"

const route = useRoute()
</script>

<template>
  <route-view />
  <Tabbar v-if="!route.meta.disbaleTabbar" />
</template>
```

**Comment by markthree** [comment]
@luoqiz 另外，我觉得商品详情页并不需要一定是二级页面，如果它是一级的，这会更容易管理。一般只有从属关系的路由和相同布局的路由才会放在一起。

**Comment by luoqiz** [comment]
这个导航我是根据示例放在 Navigation 中的，navigation放在 layout/default.vue 中的，这个如何判断？

**Comment by markthree** [comment]
@luoqiz 靓仔，你可以给个最小复现的测试仓库吗？

**Comment by luoqiz** [comment]
我上传到main 分支了，兄弟看看。 https://github.com/luoqiz/tov-template-demo

**Comment by markthree** [comment]
> 我上传到main 分支了，兄弟看看。 https://github.com/luoqiz/tov-template-demo

靓仔，已 pr → https://github.com/luoqiz/tov-template-demo/pull/1

**Comment by luoqiz** [comment]
ok
