### ISSUE TITLE
tov-template 似乎不够完善？并且什么时候出实战教程？

### ISSUE THREAD

**Issue by dmhai** [dishait/tov-template#109]
新手前端，纠结挑选开发模板中，tov技术栈看起来不错。

clone 看了下，好像完善度还不够，不够"开箱即用"。

亲，出个详细教程吧，把tov的技术栈、请求封装，store，路由封装等框架设计上的东西讲讲，然后把UI集成，添加页面，添加api，添加路由啥的二次开发的讲讲，应该就够凑出一个实战课程了，连名字我都帮你想好了，就叫【实战开发一套企业级vue3开发模板】。

嗯，收费的也行。

**Comment by markthree** [comment]
@dmhai 靓仔，很抱歉该模板没能达到你的预期。

之所以让你感觉不完善，是因为该模板并不绑定任何强业务相关的内容，也不绑定特定的 `ui` 组件库。

`tov-template` 的定位旨在还不错的 `dx` 基础上，尽量不让开发者去担心生产环境下的优化跟兼容性 (这也是我不断实时更新依赖的原因 🤣)

基于你的描述，我想你应该可能想要 

- [vbenjs/vue-vben-admin](https://github.com/vbenjs/vue-vben-admin)
- [pure-admin/vue-pure-admin](https://github.com/pure-admin/vue-pure-admin)

`tov-template` 你可以认为是它们的丐版 🐕

**Comment by markthree** [comment]
@dmhai 靓仔，至于视频教程很抱歉应该不会有。

因为该模板会实时保持跟社区最新的技术栈同步，所以很难出实战教程。

一般会以分享的形式在 b 站中进行分享，例如 [BV1FX4y1s7QY](https://www.bilibili.com/video/BV1FX4y1s7QY)

至于文档，我认为是一个非常好的提议，我应该会开多一个仓库来分享它 🥰

**Comment by dmhai** [comment]
没事，各人有各人的想法和选择，你的想法我能理解，只能说tov不符合我当前的需求。

可能我的表达不太好，让你理解错了，你上面发的2个是比较全面模板库，而我想要的是最好能直接二次开发的(有点类似后端的权限管理框架?)

比如这样的： https://github.com/xiangshu233/vue3-vant4-mobile (新发现的,非广告)

谢谢回复，issue 我关了。

**Comment by portland237930** [comment]
我在使用过程中使用嵌套路由会导致页面样式失效并且必须要跳转两次才能生效是什么情况,只有多级路由的会这样其他都不会
