### ISSUE TITLE
是否有模板脚手架？

### ISSUE THREAD

**Issue by BaiLanYu9587** [dishait/tov-template#111]
希望能像vite创建项目一样，用cmd选择自己想要的插件或者组件库，省去繁杂的配置删改，无脑的创建模板

**Comment by markthree** [comment]
@1271446615 靓仔你好，cli 脚手架版本的模板很棒，但我暂时想不出如何处理这些复杂的配置

**Comment by mlzk** [comment]
> @1271446615 靓仔你好，cli 脚手架版本的模板很棒，但我暂时想不出如何处理这些复杂的配置，期待其他更多具体的实现 `idea`

有个疑问，目前tov-template使用eslint 仅在提交时进行校验，而在编辑器开发时没有相关的错误提示，我应该如何配置才能结合vscode eslint插件做到开发时校验？

**Comment by markthree** [comment]
@BaiLanYu9587 靓仔，我认为这个模板已经足够复杂通用，短时间内不会有 cli 脚手架版本，所以我将关闭这个问题
