### ISSUE TITLE
package.json中的overrides是否可以剔除，会有影响吗

### ISSUE THREAD

**Issue by baixjian** [dishait/tov-template#117]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@baixjian 靓仔，可以删除，但我觉得保留着会更好，因为 overrides 其实是对一些重复的依赖进行合并，另外用一些更现代的依赖代替了很多废弃的依赖

**Comment by markthree** [comment]
我认为已经没什么需要补充的了 🤣
