### ISSUE TITLE
建议：类Nuxt3文件系统布局

### ISSUE THREAD

**Issue by Baiyuetribe** [dishait/tov-template#12]
传统vue项目入口都在src目录下，一旦搭配后端同时开发，你会发现src下可能要嵌套三四级目录才能找到组件。
Nuxt3干掉了`src`，大胆的把里面的组件、页面、布局放在第一级目录里，实际上大有好处，`tov-template`是个很前沿的项目，可以考虑干掉`src`

**Comment by markthree** [comment]
@Baiyuetribe 我喜欢你的提议，从实现的角度上它也是可能的，但是干掉 `src` 目录太毁灭性了 😂。另外虽然 `tov-template` 是相对比较前沿的项目，但仍然是一个前后端分离的 `SPA` 模板，所以像 `Nuxt` 一样搭着后端一起开发的场景会相对比较少。

**Comment by markthree** [comment]
可能的话，我想类似 `Nuxt3` 的架构应该是另外的项目，而不在 `tov-template` 😁，也许我会开多这样一个项目

**Comment by Baiyuetribe** [comment]
其实我参考你的已经写了一个，局部还待完善。我说的后端不是搭配Nuxt3，是其他后端语言，比如go。全栈开发哪种。

**Comment by markthree** [comment]
@Baiyuetribe 可以的，你可以在这里上你的仓库链接，也许我可以为你提 `pr` 😂

**Comment by Baiyuetribe** [comment]
> @Baiyuetribe 可以的，你可以在这里上你的仓库链接，也许我可以为你提 `pr` 😂
感谢支持，已完成和待完成的都简单汇总了一下。大佬有空可以协助完善下
https://github.com/Baiyuetribe/naive-ui-like-nuxt3-template

**Comment by markthree** [comment]
@Baiyuetribe ok，我先一键三连你

**Comment by markthree** [comment]
@Baiyuetribe 已创建新仓库 👉 [tov-template-lite](https://github.com/dishait/tov-template-lite)
