### ISSUE TITLE
如何进行路由的重定向

### ISSUE THREAD

**Issue by B1ackg0d** [dishait/tov-template#123]
靓仔你好，
请问下在你的项目中如何配置文件路由的重定向？基于项目中使用的unplugin-vue-router

**Comment by markthree** [comment]
@B1ackg0d 靓仔，你好

我认为我们可以使用 meta 来实现这个功能

我们可以在 `src/plugins/router.ts` 中补充

```diff
import { createGetRoutes, setupLayouts } from 'virtual:meta-layouts'
import { createRouter, createWebHistory } from 'vue-router'
import { routes as fileRoutes } from 'vue-router/auto/routes'

declare module 'vue-router' {
	// 在这里定义你的 meta 类型
	// eslint-disable-next-line no-unused-vars
	interface RouteMeta {
		title?: string
		layout?: string
+		redirect?: string
	}
}

export const router = createRouter({
	history: createWebHistory(),
	routes: setupLayouts(fileRoutes),
})

+ router.beforeEach((to) => {
+	const { redirect } = to.meta
+	if (redirect) {
+		return { path: redirect }
+	}
+ })

export const getRoutes = createGetRoutes(router)

export default router
```

然后我们有个 `src/pages/foo.vue`，想要将它重定向到 `/`

```diff
<template>
  <div>foo</div>
</template>

<route lang="json">
{
  "meta": {
+    "redirect": "/"
  }
}
</route>
```

**Comment by markthree** [comment]
线上 demo → [stackblitz](https://stackblitz.com/edit/github-zruvf3)

**Comment by B1ackg0d** [comment]
谢谢靓仔，晚点我试试

**Comment by B1ackg0d** [comment]
> 线上 demo → [stackblitz](https://stackblitz.com/edit/github-zruvf3)

你好靓仔，
如果我希望实现组件基本级别的导航守卫进行路由，也是在这里进行吗？是否有更好的方式？

**Comment by markthree** [comment]
> > 线上 demo → [stackblitz](https://stackblitz.com/edit/github-zruvf3)
> 
> 你好靓仔， 请问如果希望实现组件基本级别的导航守卫进行路由，也是在这里进行吗？是否有更好的方式？

靓仔，组件里可以通过 [useRoute](https://router.vuejs.org/zh/api/#Functions-useRoute) 和 [useRouter](https://router.vuejs.org/zh/api/#Functions-useRouter) 来操作哦

**Comment by markthree** [comment]
@B1ackg0d 靓仔，如果这个问题已经解决，请 `close` 掉

**Comment by markthree** [comment]
@B1ackg0d 靓仔，很抱歉，我认为已经没有什么其他的要补充的了，我将 close 掉这个问题
