### ISSUE TITLE
Failed to resolve import "ant-design-vue/es/layout/style/css" from "src\components\HelloWorld.vue". Does the file exist?

### ISSUE THREAD

**Issue by B1ackg0d** [dishait/tov-template#124]
靓仔你好，尝试在项目中引入ant-design-vue这个库，pnpm install ant-design-vue。使用的时候报错了。按照文档应该是安装完依赖会自动引入？
![image](https://github.com/dishait/tov-template/assets/50610732/f341a0b1-b22d-4923-a1e4-5424cc25ddf0)

**Comment by markthree** [comment]
@B1ackg0d 靓仔，我看了下配置，可以在 `presets/index.ts` 中补上

![image](https://github.com/dishait/tov-template/assets/36569518/ac836133-0c86-4eae-8d3c-bb60c88d8780)

**Comment by markthree** [comment]
@B1ackg0d 已修复 → [44290d8](https://github.com/dishait/tov-template/commit/44290d862b1ccdd16f80d5db1a79f443ba9619f1)

**Comment by B1ackg0d** [comment]
> @B1ackg0d 已修复 → [44290d8](https://github.com/dishait/tov-template/commit/44290d862b1ccdd16f80d5db1a79f443ba9619f1)

靓仔，按照你的操作。这个报错以及解决。我尝试引入antd的全局暗色样式，这个样式是存在的
![image](https://github.com/dishait/tov-template/assets/50610732/5f77c7c7-8dfb-4fd1-a276-0c958eaccca5)
报错了：
Failed to resolve import "ant-design-vue/dist/antd.dark.css" from "src\main.ts". Does the file exist?

**Comment by markthree** [comment]
@B1ackg0d 靓仔，我并不是特别了解 `antd` 的具体内容哦，也不是特别清楚它的包有没有导出 `ant-design-vue/dist/antd.dark.css`，我认为你可以根据它的最新的文档来处理这个样式 🥰

**Comment by B1ackg0d** [comment]
> @B1ackg0d 靓仔，我并不是特别了解 `antd` 的具体内容哦，也不是特别清楚它的包有没有导出 `ant-design-vue/dist/antd.dark.css`，我认为你可以根据它的最新的文档来处理这个样式 🥰
> 
> tip: 非模板问题

好的靓仔，谢谢你
