### ISSUE TITLE
设置嵌套动态路由

### ISSUE THREAD

**Issue by B1ackg0d** [dishait/tov-template#127]
你好靓仔，
我正在尝试基于你的项目设置嵌套的动态路由，目前无法正常工作。能否帮忙看一下我的设置是否正确，感谢~
以下是我的代码和目录组织：
```
// router.ts
fileRoutes.push(policy as RouteRecordRaw)
const trigger = {
	path: '/:userid/trigger/:triggerid',
	component: () => import('../pages/[userid]/trigger/[triggerid].vue'),
	meta: {
		layout: 'custom', // 通过元信息来管理布局
	},
}

fileRoutes.push(trigger as RouteRecordRaw)
export const router = createRouter({
	history: createWebHistory(),
	routes: setupLayouts(fileRoutes),
})


export const getRoutes = createGetRoutes(router)

export default router
```
![image](https://github.com/dishait/tov-template/assets/50610732/d34f0160-993c-4eab-8337-be35a9ad4485)

**Comment by B1ackg0d** [comment]
> 否正确，感谢~
> 以下是我的代码和目录组织：

如果我把我的custom.vue代码放在default.vue是可以正常工作的。

**Comment by markthree** [comment]
@B1ackg0d 另外是确保你的布局文件在 `src/layouts` 中.

ref -> [非默认布局](https://github.com/dishait/tov-template#%E9%9D%9E%E9%BB%98%E8%AE%A4%E5%B8%83%E5%B1%80)

**Comment by B1ackg0d** [comment]
> @B1ackg0d 靓仔，请不要手动添加，因为 unplugin-vue-router 已经帮我们做了路由自动注册，请移除以下路由
> 
> ```diff
> - const trigger = {
> -	path: '/:userid/trigger/:triggerid',
> -	component: () => import('../pages/[userid]/trigger/[triggerid].vue'),
> -	meta: {
> -		layout: 'custom', // 通过元信息来管理布局
> -	},
> -}
> ```

原来如此，https://github.com/dishait/vite-plugin-vue-meta-layouts 我是参考的这里的示例进行设置的。
![image](https://github.com/dishait/tov-template/assets/50610732/e56c6837-761a-42dd-942b-e899cc281ace)

**Comment by B1ackg0d** [comment]
> @B1ackg0d 靓仔，你应该看 https://github.com/dishait/vite-plugin-vue-meta-layouts#unplugin-vue-router 以及 https://github.com/posva/unplugin-vue-router

你好，靓仔。设置了动态路由后，在测试的时候一切正常（可以各种路由跳转）。pnpm preview 后无法正常跳转，浏览器空白，控制台报错：
```
because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
请问是否是vite的配置问题。

**Comment by markthree** [comment]
没有其他内容需要补充，我关闭了这个问题
