### ISSUE TITLE
静态文件在改 base 之后，路径错误

### ISSUE THREAD

**Issue by ottocsb** [dishait/tov-template#128]
### nodejs 版本
`v18`

<br />

### 包管理器及其版本
 `pnpm`

<br />

### 系统

 `win10`

<br />
<br />

### 描述

佬，关于`vite.config`中配置了`base`上下文后，该如何引用`public`目录中的静态资源呢，在引用处加上`base`内容，dev环境可以正常展示，打包时提示错误。
如果不加`base`内容，则无法加载。
<br />

### 预期结果

正常加载。

<br />

### 最小测试仓库

最小复现环境就是`base`配置任意值后，`notFound`页资源无法加载。

**Comment by ottocsb** [comment]
目前改成:` import notFound form "/public/notFount/xxx.svg"`，但引用图片的组件都要加几个`import`略显繁琐

**Comment by markthree** [comment]
@ottocsb 靓仔，你好，我将稍后查看这个问题

**Comment by markthree** [comment]
@ottocsb 靓仔你好，已解决 -> [148d9204](https://github.com/dishait/tov-template/commit/148d9204e734aeccad46d16ac4267b90447971be)

通过这个方案，我们可以在任何位置使用 `safeResolve('你的路径')` 来做到 `base` 安全解析

**Comment by markthree** [comment]
@ottocsb 具体可见 -> [base 安全的路径解析](https://github.com/dishait/tov-template/#38-base-%E5%AE%89%E5%85%A8%E7%9A%84%E8%B7%AF%E5%BE%84%E8%A7%A3%E6%9E%90)
