### ISSUE TITLE
建议：修改为monorepo多包模式

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#132]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@luoqiz 靓仔，这里上monorepo多包的原因是什么呢？可以详细描述下具体的场景 🤣

**Comment by luoqiz** [comment]
我现在有三个C端项目，一个C端WEB管理后台，一个C端桌面版本（WEB页面），一个C端H5，除了页面展示不一样之外，其他基本一致，现在三个项目来回拷贝，而且后台的代码生成器也只是桌面版本的。现在准备都使用这个模板重构，发现monorepo的多包模式更适合这种实际公司中的多端开发，所以提出了此建议。

**Comment by markthree** [comment]
> 我现在有三个C端项目，一个C端WEB管理后台，一个C端桌面版本（WEB页面），一个C端H5，除了页面展示不一样之外，其他基本一致，现在三个项目来回拷贝，而且后台的代码生成器也只是桌面版本的。现在准备都使用这个模板重构，发现monorepo的多包模式更适合这种实际公司中的多端开发，所以提出了此建议。

这种确实需要 monorepo 多包，但 tov-template 当前的设计完全是单 web app，我认为需要一定时间来探索一种更通用的方式来处理这种多项目的场景。

当前在使用和 tov-template 上差不多，同时更友好的支持 monorepo 的方案，我认为是 nuxt 的 spa 模式下的 layer 功能。

稍候我将写一个最小的仓库来实现它

**Comment by markthree** [comment]
@luoqiz 这是一个例子 👉 [nuxt-mon](https://github.com/markthree/nuxt-mon)

**Comment by luoqiz** [comment]
我看了这个方案，又引入了nuxt，不过这种方案也是非常棒的，也是我最初想到过的继承方案，但是当时不知道nuxt3 加入了layer 模块。我是主做Java后台的，不知道你是否了解java的微服务，我的思路里是按照微服务形式进行逻辑分模块和ui分离后的组合，这样复用程度更高，而且作为项目模板的时候可以自由组合需要的逻辑和ui（比如使用el、vant、ant等）。
