### ISSUE TITLE
error： 中英文切换时，使用的第三方ui组件未切换

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#134]
### 描述

使用的 element-plus， 中英文切换时，使用的第三方组件未切换

参考链接  https://element-plus.org/zh-CN/component/config-provider.html

![image](https://github.com/dishait/tov-template/assets/22161059/0a56e009-0e36-4f3a-8b68-a66eaa62d660)

**Comment by markthree** [comment]
@luoqiz 靓仔，已修复 → [5d1fd3f](https://github.com/dishait/tov-template/commit/5d1fd3f3b6c894caf0e4b005b9bf932673b22e1f)

具体使用实例可见 → [tov-template-element-plus-i18n](https://github.com/markthree/tov-template-element-plus-i18n)
