### ISSUE TITLE
feat!: 将开发环境配置和生产打包配置分开文件进行配置

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#136]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@luoqiz 靓仔，可以详细描述下对应的场景吗？
因为如果将开发和生产分开的话，有些靓仔可能会修改错对应环境的配置文件，例如配了开发时的配置文件，但生产时配置文件却没有更改，导致上下文丢失。

**Comment by luoqiz** [comment]
开发环境、测试环境和生产环境本身就不是一致的，通用的配置仍放在env中，其他的配置应该是各个环境跑各自的，像你说的这种情况只能说这类公司不够规范，况且开发、测试和生产每次都需要修改岂不是更麻烦？我接触的公司，没有不把环境区分开的，最规范的是开发和测试在项目中写配置，生产环境是运维写在k8s或者docker的配置中。

**Comment by markthree** [comment]
> 开发环境、测试环境和生产环境本身就不是一致的，通用的配置仍放在env中，其他的配置应该是各个环境跑各自的，像你说的这种情况只能说这类公司不够规范，况且开发、测试和生产每次都需要修改岂不是更麻烦？我接触的公司，没有不把环境区分开的，最规范的是开发和测试在项目中写配置，生产环境是运维写在k8s或者docker的配置中。

@luoqiz  靓仔，我认为我们可以通过一些机制来智能支持多种配置文件的方式，默认情况下只支持一个配置文件，当存在多个配置文件时，自动切换过去

下边是一个 WIP 方案 ↓

eg:
1. 仅 vite.config.ts 时，通用选择该配置
2. vite.config.ts + vite.config.dev.ts，开发时合并两者的配置，同时 vite.config.dev.ts 的配置优先级更高
3. vite.config.ts + vite.config.prod.ts 生产时合并两者的配置，同时 vite.config.prod.ts 的配置优先级更高
4. vite.config.ts + vite.config.test.ts 测试时合并两者的配置，同时 vite.config.test.ts 的配置优先级更高

以此类推来支持更多的 mode 和通用配置

该方案一定程度上即满足了喜欢单配置的靓仔，也支持多配置的需求。(no break change 🤣)

如果对此方案有什么修改的意见，欢迎指出

**Comment by markthree** [comment]
> > 开发环境、测试环境和生产环境本身就不是一致的，通用的配置仍放在env中，其他的配置应该是各个环境跑各自的，像你说的这种情况只能说这类公司不够规范，况且开发、测试和生产每次都需要修改岂不是更麻烦？我接触的公司，没有不把环境区分开的，最规范的是开发和测试在项目中写配置，生产环境是运维写在k8s或者docker的配置中。
> 
> @luoqiz 靓仔，我认为我们可以通过一些机制来智能支持多种配置文件的方式，默认情况下只支持一个配置文件，当存在多个配置文件时，自动切换过去
> 
> 下边是一个 WIP 方案 ↓
> 
> eg:
> 
> 1. 仅 vite.config.ts 时，通用选择该配置
> 2. vite.config.ts + vite.config.dev.ts，开发时合并两者的配置，同时 vite.config.dev.ts 的配置优先级更高
> 3. vite.config.ts + vite.config.prod.ts 生产时合并两者的配置，同时 vite.config.prod.ts 的配置优先级更高
> 4. vite.config.ts + vite.config.test.ts 测试时合并两者的配置，同时 vite.config.test.ts 的配置优先级更高
> 
> 以此类推来支持更多的 mode 和通用配置
> 
> 该方案一定程度上即满足了喜欢单配置的靓仔，也支持多配置的需求。(no break change 🤣)
> 
> 如果对此方案有什么修改的意见，欢迎指出

@luoqiz 靓仔，已在 [cd3092](https://github.com/dishait/tov-template/commit/cd30922fae14af3ff86bc77456e2ff1de942e630) 中支持该特性，可以下载最新模板进行尝试。

该特性由 [vite-layers](https://github.com/markthree/vite-layers) 提供支持 🥰

**Comment by luoqiz** [comment]
就是这种方式，   env放一些公共配置，env.prod 放特有配置，但是当配置重复的时候，以prod为准

**Comment by markthree** [comment]
> 就是这种方式， env放一些公共配置，env.prod 放特有配置，但是当配置重复的时候，以prod为准

靓仔，环境变量方面，vite 已默认支持，无需担心，这里补充实现了 vite 配置本身的环境层，可以尝试一下
