### ISSUE TITLE
自动导入自定义的api失效

### ISSUE THREAD

**Issue by 316374157** [dishait/tov-template#14]
自动导入自定义插件失效，在自己的项目中没有生成，用了模板项目“tov-template”，删除auto-import.d.ts后重新启动项目，会重新生成该文件，但是文件中无引入的自定义api
![image](https://user-images.githubusercontent.com/46001074/160095779-ff8b5bc5-d73e-4f61-a6b7-b7e38ac02c18.png)
![image](https://user-images.githubusercontent.com/46001074/160095700-bcfdb5a0-d755-4a2b-8325-9ebbd9047d4d.png)

**Comment by markthree** [comment]
靓仔你好，请问可以提供一个最小实例仓库不，我这边无法复现该问题。
具体用法可见 👉 [6. Api 自动引入](https://github.com/dishait/tov-template#6-api-%E8%87%AA%E5%8A%A8%E5%BC%95%E5%85%A5)，同时还得确保工作区是根目录哦。

**Comment by 316374157** [comment]
这个可以直接用这个模板试，把
![image](https://user-images.githubusercontent.com/46001074/160108646-1125239b-e93f-4fc6-b663-147d6f2d5b4b.png)
文件删除后，重新运行项目，新生成的这个问题件中就没有自定义的api
![image](https://user-images.githubusercontent.com/46001074/160108900-a49f0697-cf42-4c42-9913-dd324c4ae444.png)

**Comment by markthree** [comment]
`auto-imports.d.ts` 只起类型声明作用，同时自定义的 `api` 只有你的代码中有用到才会生成。例如，如果将 `useDarks` 从代码中删除了就不会生成。

**Comment by 316374157** [comment]
但是项目启动了，用到了，这个文件中也没有
![image](https://user-images.githubusercontent.com/46001074/160109785-7b36b58a-ccb1-4bd4-bd6d-1b91e5f55d19.png)
并且，页面的内容会因为这个报错而出不来，项目已经重启
![image](https://user-images.githubusercontent.com/46001074/160110200-00f2a13c-c759-408f-9872-119890464c4f.png)
![image](https://user-images.githubusercontent.com/46001074/160110106-14efa367-e71a-4991-83be-2b5bcc14d626.png)

**Comment by markthree** [comment]
靓仔你好，我这边无法复现该问题，可以提供一下你使用的包管理器，系统以及 `nodejs` 版本吗？

**Comment by 316374157** [comment]
![image](https://user-images.githubusercontent.com/46001074/160111102-86af4037-9155-4807-93e5-611582ecbddc.png)
系统版本是win10

**Comment by 316374157** [comment]
还需要什么呢？

**Comment by markthree** [comment]
目前该项目的开发环境是 `win11`，所以我无法确定是否是系统差异造成的错误。

当然你可以将 `node` 版本更新到目前的长期维护版本 `v16` 以上，具体可见 👉 [node 版本推荐](https://github.com/dishait/tov-template#node-%E7%89%88%E6%9C%AC%E6%8E%A8%E8%8D%90-)。同时可以执行 `pnpm up` 更新所有依赖后重试。

**Comment by 316374157** [comment]
okok，我先更一下node试试

**Comment by markthree** [comment]
> 目前该项目的开发环境是 `win11`，所以我无法确定是否是系统差异造成的错误。
> 
> 当然你可以将 `node` 版本更新到目前的长期维护版本 `v16` 以上，具体可见 👉 [node 版本推荐](https://github.com/dishait/tov-template#node-%E7%89%88%E6%9C%AC%E6%8E%A8%E8%8D%90-)。同时可以执行 `pnpm up` 更新所有依赖后重试。

如果以上步骤仍然不行，欢迎 `pr`

**Comment by 316374157** [comment]
node版本问题，已解决，谢谢

**Comment by markthree** [comment]
不客气
