### ISSUE TITLE
feat(scripts): 安全的初始化 

### ISSUE THREAD

**Issue by B1ackg0d** [dishait/tov-template#147]
你好靓仔，纯净版的分支指的是没有现在仓库的示例index页面的相关内容，还有存在的API mock，这样可以快速开发，真正做到开箱即用。以我自己举例，我要使用这个项目开发新项目的时候，总是要删除一些目前的模板里的一些东西。
![image](https://github.com/dishait/tov-template/assets/50610732/f69f97cd-e8d1-4819-a566-5a0604acbf22)

**Comment by markthree** [comment]
@B1ackg0d 靓仔，我认为纯净版本的分支在保持特性更新的情况下处理冲突是频繁的。一个更好的办法是提供一个命令脚本来进行安全的初始化。

**Comment by B1ackg0d** [comment]
> @B1ackg0d 靓仔，我认为纯净版本的分支在保持特性更新的情况下处理冲突是频繁的。一个更好的办法是提供一个命令脚本来进行安全的初始化。

是的靓仔，脚本会更好更灵活。

**Comment by withrjp** [comment]
每次clone下来都要删一些东西，期待这个功能。

**Comment by markthree** [comment]
@B1ackg0d @withrjp 已支持该功能脚本，可以在最新模板中执行 `pnpm safe:init`

> 目前该功能是实验性的 🥰

**Comment by B1ackg0d** [comment]
> @B1ackg0d @withrjp 已支持该功能脚本，可以在最新模板中执行 `pnpm safe:init`
> 
> > 目前该功能是实验性的 🥰
> > 具体脚本 → [scripts/safe-init.cjs](https://github.com/dishait/tov-template/blob/main/scripts/safe-init.cjs)

靓仔，style目录是否也应该删除？

**Comment by markthree** [comment]
> > @B1ackg0d @withrjp 已支持该功能脚本，可以在最新模板中执行 `pnpm safe:init`
> > > 目前该功能是实验性的 🥰
> > > 具体脚本 → [scripts/safe-init.cjs](https://github.com/dishait/tov-template/blob/main/scripts/safe-init.cjs)
> 
> @markthree 靓仔，style目录是否也应该删除？

可以删除，但 style 中有些不错的默认样式，我认为我们可以给出一个选项来确定是否删除 style 目录

**Comment by markthree** [comment]
> @markthree 靓仔，style目录是否也应该删除？

@B1ackg0d 已支持

**Comment by markthree** [comment]
对该功能，我想已经没有什么需要补充的

如果有其他需要补充的话，欢迎提新 issue 🥰
