### ISSUE TITLE
BUG: 使用 element-plus v-loading 指令时，报错

### ISSUE THREAD

**Issue by zhaojun1998** [dishait/tov-template#15]
### nodejs 版本

16.13.1

### 包管理器及其版本 

pnpm

### 系统
macOS

### 描述

使用目前最新的代码，然后执行 `pnpm install element-plus` 安装 `element-plus`，使用 [v-loading 指令](https://element-plus.gitee.io/zh-CN/component/loading.html)，会报错：

```
[plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/loading-directive/style/css" from "src/pages/Index.vue". Does the file exist?
```

### 预期结果

`v-loading` 功能正常运行

### 最小测试仓库

目前最新版执行 `pnpm install element-plus` 后，在任意元素上增加 `v-loading="true"` 即可复现

**Comment by markthree** [comment]
@zhaojun1998 靓仔你好，`element-plus` 本身解析器 `bug`，具体可见 👉 [自动导入v-loading编译无法通过](https://github.com/element-plus/element-plus/issues/4855)

**Comment by zhaojun1998** [comment]
收到。谢谢靓仔。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月30日(周三) 晚上6:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dishait/tov-template] BUG: 使用 element-plus v-loading 指令时，报错 (Issue #15)




 
@zhaojun1998 靓仔你好，element-plus 本身解析器 bug，具体可见 👉 自动导入v-loading编译无法通过
