### ISSUE TITLE
带 base 生产时无法正确重定向

### ISSUE THREAD

**Issue by ydedev** [dishait/tov-template#152]
### nodejs 版本

v21.5.0

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

pnpm 8.14.0

<br />

### 系统

macos
<br />

https://xxxxxxx.com/zzz/xxxxx/ 是在defineConfig中配置的base字段，第一次用，感谢指教

**Comment by markthree** [comment]
@ydedev 靓仔，这里的 `debug` 需要你的最小复现仓库哦，或者具体的 `vite.config.ts` 配置。

另外是 `base` 不要用到 `https://xxxxxxx.com/zzz/xxxxx/` 而应该使用 `/zzz/xxxxx/`，因为前边的域名不应该是 `vite` 来设置的

**Comment by markthree** [comment]
@ydedev 靓仔，这里的 `debug` 需要你的最小复现仓库哦，或者具体的 `vite.config.ts` 配置。

另外是 `base` 不要用到 `https://xxxxxxx.com/zzz/xxxxx/` 而应该使用 `/zzz/xxxxx/`，因为前边的域名不应该是 `vite` 来设置的，而应该让最终的服务来控制

**Comment by markthree** [comment]
目前即使我们更改了 `base` 并打包，虽然可以通过 `pnpm run preview` 来预览

但最终跑在生产环境时，我们仍然还需要手动处理静态服务的重定向，让它永远重定向到 `base`

也许我们可以使用 [nitro-proxy](https://github.com/markthree/nitro-proxy) 来快速支持该特性 (在生产时)

**Comment by markthree** [comment]
生产上已由 [nitro-proxy](https://github.com/markthree/nitro-proxy) 支持
