### ISSUE TITLE
请问路由元信息如何扩展？

### ISSUE THREAD

**Issue by WT-SML** [dishait/tov-template#16]
本项目是基于文件路由的。
那么如果某些路由需要携带重要的 meta 信息（权限），标准做法是什么？
是 vite-plugin-pages插件的 extendRoute ？
还是重写路由文件？

**Comment by hedongshu** [comment]
```js
<route lang="yaml">
meta:
  title: 首页
  isMenu: true
  icon: mdi:home
</route>
```

我是这样写的，之后可以在页面里拿到这个meta信息。
具体可以参考一下我基于这个项目开发的一个简单的admin框架
https://github.com/hedongshu/vitesse-with-naive

**Comment by WT-SML** [comment]
感谢解答！Thanks♪(･ω･)ﾉ

**Comment by markthree** [comment]
@WT-SML 靓仔你好，具体用法也可见 [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages)
