### ISSUE TITLE
support keep-alive

### ISSUE THREAD

**Issue by baixjian** [dishait/tov-template#162]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@baixjian 靓仔，这个似乎并不是模板的问题 🤣

`keep-alive` 并非所有人都需要哦，所以这里我们不加
