### ISSUE TITLE
是否计划写成一个admin项目？

### ISSUE THREAD

**Issue by hedongshu** [dishait/tov-template#17]
现在tov是个快速启动模板，跟通常的admin项目相比只有基础配置等；缺失基本的layout和router to menu；未来有没有计划完善这个项目，做成一个基础版本的admin

**Comment by markthree** [comment]
@hedongshu 靓仔你好，内部在做，后续分享出来。不过应该是其他仓库了，tov-template 只做简单的模板。

**Comment by markthree** [comment]
@hedongshu 预计在4，5月份发布

**Comment by joyswing** [comment]
现在大家纠结的是模板更新了以后，后续怎么使用你更新的模版，尽早出来，大家可以方便使用和推广

**Comment by hedongshu** [comment]
> @hedongshu 预计在4，5月份发布

发布了吗

**Comment by markthree** [comment]
@hedongshu 靓仔你好，因为内部正在做其他的工作，所以 `admin` 开源项目将延后哦。

不过已经有后台实战项目课程了，感兴趣可以看看哦 👇👇👇

<div>
    <a href="https://study.163.com/course/courseMain.htm?courseId=1212775807&share=2&shareId=480000001892585"> 
        <img src="https://study-image.nosdn.127.net/48882f1678b84c17976f3cc059fc138b.png" />  
    </a>
</div>

### 👉 [视频课程](https://study.163.com/course/courseMain.htm?courseId=1212775807&share=2&shareId=480000001892585)

### 👉 [线上演示](http://shopadmin.dishawang.com)
- 账号: **`admin`**   
- 密码: **`admin`**

<br />

**Comment by markthree** [comment]
我认为我们没有其他的时间来将它写成 admin，如果有感兴趣的小伙伴，欢迎提一个新的仓库
