### ISSUE TITLE
git 上传代码报错

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#175]
### nodejs 版本
20
 

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

pnpm  9.0.6

(请使用 `pnpm`)

<br />

### 系统

(该项目开发环境系统为 `win11`)

<br />
<br />

## bug

![image](https://github.com/dishait/tov-template/assets/22161059/60f22a21-a178-4765-8937-a4748da73b34)

升级版本后，git 上传代码报错

**Comment by markthree** [comment]
@luoqiz 已更新，将 `@unocss/eslint-config` 设置为 `0.58.0` 即可
