### ISSUE TITLE
webview开发环境

### ISSUE THREAD

**Issue by Tiny-nx** [dishait/tov-template#18]
首先感谢您！因为跟着您分享的框架学习了好多！最近发现了一个问题，不知道别人是否也遇到了！开发环境下，webview是打不开的！只有build后发布到服务器后才能显示在webview中，当然，开发环境下浏览器是可以正常打开的！求指导！谢谢

**Comment by markthree** [comment]
靓仔你好，我没有尝试过 `webview` 的场景。不过看描述因该是 [vite](https://github.com/vitejs/vite/issues) 本身的问题，可以前往 👉 [vite issues](https://github.com/vitejs/vite/issues) 提该问题

**Comment by Tiny-nx** [comment]
好的！谢谢

**Comment by markthree** [comment]
不客气的
