### ISSUE TITLE
是否未来考虑加入屏幕适配方面的插件

### ISSUE THREAD

**Issue by wanto2014** [dishait/tov-template#181]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@wanto2014 靓仔你好，这块不考虑哦，因为实际开发过程中业务是强烈变动的，推荐直接使用 unocss 的样式来处理各个屏幕下的样式
