### ISSUE TITLE
naive ui 暗黑模式

### ISSUE THREAD

**Issue by ottocsb** [dishait/tov-template#19]
hi 我该如何使用windi css 渲染naive ui的组件呢， 切换模式时组件的边框和样式切换成暗黑模式了，但组件内的文本并没有渲染，还是说我需要使用naive ui的暗黑模式？
我是个菜鸟，问的问题可能很愚蠢，希望不要介意
![image](https://user-images.githubusercontent.com/83228451/164162160-2c2ba408-3400-423a-9a31-3a852a218368.png)
如上图，按钮中的文本并没有渲染
![image](https://user-images.githubusercontent.com/83228451/164162299-7aaddbe3-edab-4a49-a500-446b1ae9d7e9.png)

**Comment by markthree** [comment]
你应该优先使用 `naive-ui` 的暗黑模式，以下是简单的示例代码

```html
<!-- App.vue 中 -->
<script setup lang="ts">
	import { darkTheme } from 'naive-ui'
	const { isDark } = useDarks()
	const theme = computed(() =>
		isDark.value ? darkTheme : null
	)
</script>

<template>
	<n-config-provider :theme="theme">
		<router-view />
         </n-config-provider>
</template>
```

**Comment by ottocsb** [comment]
谢谢，我尝试使用过naive ui的暗黑模式没有生效应该是我的语法有问题还不熟悉ts，十分感谢，我再去尝试
