### ISSUE TITLE
使用vite-auto-import-resolvers预设配置auto-import后,definePage()宏自动导入失效

### ISSUE THREAD

**Issue by wanto2014** [dishait/tov-template#194]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by wanto2014** [comment]
可以实现效果,但是eslint报错

**Comment by markthree** [comment]
@wanto2014 已修复，可重新 clone 模板，或者在自己的模板中添加以下内容

![image](https://github.com/user-attachments/assets/742a98d3-2e19-4568-8d5c-ec792634b377)
