### ISSUE TITLE
Vite 中的Base修改后会影响到路由

### ISSUE THREAD

**Issue by woddle** [dishait/tov-template#199]
将Vite.config.ts中修改了Base 之后，编译后的路由会收到影响

**Comment by ShouJen** [comment]
设置base:'./'之后打包，生产环境浏览报错index-3XgwbOFl.js:42 Uncaught Error: Invalid path "./"
    at tokenizePath (index-3XgwbOFl.js:42:10700)
    at createRouteRecordMatcher (index-3XgwbOFl.js:42:11784)
    at s (index-3XgwbOFl.js:42:12505)
    at index-3XgwbOFl.js:42:13935
    at Array.forEach (<anonymous>)
    at createRouterMatcher (index-3XgwbOFl.js:42:13924)
    at createRouter (index-3XgwbOFl.js:42:21047)
    at index-3XgwbOFl.js:42:28780

**Comment by ShouJen** [comment]
把 import Tov from './presets'; 中的 import Router from 'unplugin-vue-router/vite'; 自动路由导入注释，然后去routes中手动配置路由再重新打包即可解决问题

**Comment by markthree** [comment]
这是设计上的问题，始终保持开发时和生产时 `base` 的一致性可参考 [base 安全的路径解析](https://github.com/dishait/tov-template?tab=readme-ov-file#38-base-%E5%AE%89%E5%85%A8%E7%9A%84%E8%B7%AF%E5%BE%84%E8%A7%A3%E6%9E%90)

![image](https://github.com/user-attachments/assets/93b35652-9845-42b4-94a7-f8043b3f029a)
![image](https://github.com/user-attachments/assets/e2f90e53-548c-4a6d-b340-321aacef079c)
