### ISSUE TITLE
修改内容，hmr 后再刷新浏览器，布局系统匹配出错

### ISSUE THREAD

**Issue by xwx-master** [dishait/tov-template#20]
### nodejs 版本

v16.14.1

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

pnpm6.32.8、npm8.5.0、yarn1.22.0

(推荐使用 `pnpm`)

<br />

### 系统

win11      chrome版本【 99.0.4844.82（正式版本） （64 位）】

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

修改页面热更新后F5刷新浏览器，layout匹配错误
eg:

1. 给default Layout随便加点文案，例如加入一个 ```<h1>default</h1>```
2. 浏览器进入notFound页面
3. 修改notFount页面中文案，例如404改为405，热更新后浏览器可见文案更新为405
4. 浏览器F5刷新页面后可以看到刚刚再default layout中新增的元素，同时你再控制台打印router的meta信息会发现layout字段的信息丢失

<br />

### 预期结果

layout通过meta.layout正确匹配

<br />

### 最小测试仓库

tov-template

**Comment by markthree** [comment]
@xwx-master 已确认 `bug`，修复中

**Comment by markthree** [comment]
@xwx-master 靓仔你好，该问题已修复。请更新依赖 `"vite-plugin-pages` 到 `^0.23.0`。具体可见该提交 👉 [a870](https://github.com/dishait/tov-template/commit/a870ece4e7963b2dd526ed75f33d08baf3a7c275)
