### ISSUE TITLE
是否能适配一个electron模板

### ISSUE THREAD

**Issue by HandsomeMonkey** [dishait/tov-template#21]
### nodejs 版本

TODO

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

TODO

(推荐使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@HandsomeMonkey 如果可以，我想会另外开多一个 `electron` 模板仓库

**Comment by yigehaobb** [comment]
我也想要一个electron的框架，每次封装electron都挺麻烦的…………哈哈好像我一直购买蒂萨学院课程只是没怎么看

**Comment by markthree** [comment]
@yigehaobb 靓仔你好，可以用社区的 [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) 哦

**Comment by hedongshu** [comment]
https://github.com/hedongshu/vitesse-electron.git
可以看看这个

**Comment by markthree** [comment]
close: [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) 已经足够稳定好用，如果有需求推荐使用
