### ISSUE TITLE
打包时 removelog 报错

### ISSUE THREAD

**Issue by liujunleo** [dishait/tov-template#23]
### nodejs 版本

v16.14.2

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

pnpm

(推荐使用 `pnpm`)

<br />

### 系统

mac

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

pnpm build 错误
![image](https://user-images.githubusercontent.com/15761835/168464170-ab564792-21e1-4f8f-aaf5-89d58c8bfafc.png)

<br />

### 预期结果

解决打包问题

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@liujunleo 靓仔你好，已确认 `bug`

**Comment by liujunleo** [comment]
> 

大佬神速

**Comment by liujunleo** [comment]
> @liujunleo 靓仔你好，已确认 `bug`

大佬神速

**Comment by markthree** [comment]
@liujunleo 可以先在 `presets/tov.ts` 里将 `117` 行的 `Rmovelog()` 注释掉
![image](https://user-images.githubusercontent.com/36569518/168464690-3a0dd7b1-3ad3-4b52-801e-6264c352e55c.png)

**Comment by liujunleo** [comment]
> @liujunleo 可以先在 `presets/tov.ts` 里将 `117` 行的 `Rmovelog()` 注释掉 ![image](https://user-images.githubusercontent.com/36569518/168464690-3a0dd7b1-3ad3-4b52-801e-6264c352e55c.png)

@markthree 是的，已经试过，注释后正常打包

**Comment by markthree** [comment]
@liujunleo 靓仔你好，该问题已修复。可以更新 [vite-plugin-removelog](https://github.com/dishait/vite-plugin-removelog) 为 `^0.0.3` 哦。

## 具体做法
1. 更改 `package.json` 里的版本号
![image](https://user-images.githubusercontent.com/36569518/168469938-022f2220-f8ae-4805-90dd-31fda61f3025.png)

2. 重新 `install`

```shell
pnpm i
```

**Comment by liujunleo** [comment]
> @liujunleo 靓仔你好，该问题已修复。可以更新 [vite-plugin-removelog](https://github.com/dishait/vite-plugin-removelog) 为 `^0.0.3` 哦。
> 
> ## 具体做法
> 1. 更改 `package.json` 里的版本号
>    ![image](https://user-images.githubusercontent.com/36569518/168469938-022f2220-f8ae-4805-90dd-31fda61f3025.png)
> 2. 重新 `install`
> 
> ```shell
> pnpm i
> ```

@markthree 收到，感谢

**Comment by liujunleo** [comment]
@markthree 你好，使用’^0.0.3‘版本的removelog插件后，如无引用ant-design-vue组件库时，可正常打包；
如有ant-design-vue组件库使用时（其他库未知），因组件库内有部分警告日志，且removelog插件默认移除[console.log, console.warn, console.error]，故打包会出现如下错误：
![image](https://user-images.githubusercontent.com/15761835/168473334-018ae5fd-f001-4d7c-80e9-ac0eb2d0f71a.png)

以上，供参考

**Comment by markthree** [comment]
@liujunleo 靓仔你好，已确认 `bug`, 后边 `removelog` 的范围将移除 `node_modules` 下 `package`

**Comment by markthree** [comment]
@liujunleo 靓仔你好，该问题已修复，可更新 [vite-plugin-removelog](https://github.com/dishait/vite-plugin-removelog) 到 `^0.0.4`

**Comment by liujunleo** [comment]
@markthree 感谢，大佬神速
