### ISSUE TITLE
自动引入，Vetur报错要怎么解决，要忽略吗

### ISSUE THREAD

**Issue by qq2627767202** [dishait/tov-template#26]
![image](https://user-images.githubusercontent.com/31646567/170979902-e7b49f4d-f871-4964-85b4-6dcde5161637.png)

**Comment by markthree** [comment]
@qq2627767202 靓仔你好，请用 [volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar)

**Comment by qq2627767202** [comment]
我vs code这个volar安装不上呀，
![image](https://user-images.githubusercontent.com/31646567/170980938-8e42ed9e-778c-446d-9566-3571527e8e6d.png)

**Comment by qq2627767202** [comment]
无法安装扩展“vue.volar”，因为它与 VS Code“1.60.1”不兼容。: Error: 无法安装扩展“vue.volar”，因为它与 VS Code“1.60.1”不兼容。

**Comment by qq2627767202** [comment]
我更新一下VS code
