### ISSUE TITLE
为什么我在src底下新增assets文件夹后，启动看似启动成功，但是页面一直在加载中，打不开

### ISSUE THREAD

**Issue by huangkaiyan10** [dishait/tov-template#27]
![3a1734f11c4c4d93c2c60e41a16fd16](https://user-images.githubusercontent.com/5146180/173211259-a8ea7ab8-8554-441c-9438-9a5dac322685.png)

![a533577cf3905964406a5509b740bfe](https://user-images.githubusercontent.com/5146180/173211271-3d8603f4-1f32-4673-8936-bf4c09ead19c.png)

![a67605e5c8f816e9fb00563c4261338](https://user-images.githubusercontent.com/5146180/173211282-7c3d44fa-9f5d-469e-8195-d3383d25cc33.png)

[assets.zip](https://github.com/dishait/tov-template/files/8885052/assets.zip)

**Comment by huangkaiyan10** [comment]
console 控制台没报错。

**Comment by markthree** [comment]
@huangkaiyan10 靓仔你好，`windicss` 的 `vite` 扫描机制问题。可以在 `presets/tov.ts` 中的补上以下代码 👇

![image](https://user-images.githubusercontent.com/36569518/173214856-9abddf95-87a6-4dcf-8557-c492aec27617.png)
