### ISSUE TITLE
Failed to resolve import "element-plus/es/components/submenu/style/css" from "src\pages\main\index.vue". Does the file exist?

### ISSUE THREAD

**Issue by huangkaiyan10** [dishait/tov-template#28]
![image](https://user-images.githubusercontent.com/5146180/173237288-13434c0f-153f-4c42-ad08-2254c524f18f.png)

**Comment by huangkaiyan10** [comment]
main.vue


<template>
    
    <div class="main">
        <div :class="{'main-header': !isSmsMainLogin, 'main-header-login': isSmsMainLogin}">
          <div class="cphm-logo"></div>
          {{sysName}}
          <div class="user-div row-nowrap">
            <div class="user-icon"></div>
            <div class="user-name">{{userName}}</div>
            <div class="message-icon"></div>
            <el-button type="primary" class="logout-btn" icon="el-icon-switch-button" @click="logout"></el-button>
          </div>
        </div>
        <div :class="{'main-body': !isSmsMainLogin, 'main-body-login': isSmsMainLogin}">
            <div class="memu-nav">
              <el-menu
                class="el-menu-nav"
                :default-active="defaultActive"
                @open="handleOpen"
                @close="handleClose"
                active-text-color="#ffffff"
                background-color="#373747">
                <el-submenu
                  v-for="item in menuData"
                  :key="item.permissionId+''"
                  :index="item.permissionId+''">
                  <template slot="title">
                    <div class="menu-div" :class="{'menu-div-active': defaultDivActive == item.permissionId}">
                      <span class="menu-line"></span>
                      <span class="icon-font" :class="item.name"></span>
                      <span class="memu-label">{{item.label}}</span>
                    </div>
                  </template>
                  <el-menu-item
                      v-for="subItem in item.children"
                      :key="subItem.permissionId+''"
                      :index="subItem.permissionId+''"
                      @click="selectItems('/main/'+subItem.name)">
                    {{subItem.label}}
                  </el-menu-item>
                </el-submenu>
              </el-menu>
              <div class="memu-bottom">
                
                <div class="TCT-logo"></div>
              </div>
            </div>
            <div class="main-content">
                <main-content></main-content>
                <div class="footer">{{copyRight}}</div>
            </div>
        </div>
    </div>
</template>

**Comment by huangkaiyan10** [comment]
![image](https://user-images.githubusercontent.com/5146180/173237517-d64e17ba-13c2-4e2f-986a-3d836d7452d8.png)
![image](https://user-images.githubusercontent.com/5146180/173237557-a4bee8c9-17e5-4bb2-8738-81683d2cefc2.png)

**Comment by markthree** [comment]
@huangkaiyan10 靓仔你好，请提供最小复现仓库

**Comment by markthree** [comment]
@huangkaiyan10 靓仔你好，请提供最小复现仓库，未提供最小复现仓库的 `unknown` 的 `issue` 将在两天后自动 `close` 哦

**Comment by huangkaiyan10** [comment]
链接：https://pan.baidu.com/s/193UQtOq6xF1VbOiq0exI0g 
提取码：7mfl

**Comment by markthree** [comment]
@huangkaiyan10 靓仔你好
1. `el-submenu` 并不存在，而应该使用 `el-sub-menu`。具体可见文档 👉 [element-plus/menu](https://element-plus.gitee.io/zh-CN/component/menu.html#collapse-%E6%8A%98%E5%8F%A0%E9%9D%A2%E6%9D%BF)
![image](https://user-images.githubusercontent.com/36569518/173499485-2322bc3c-bdf5-4dac-91b5-cb6ec50eb289.png)

2. `sfc` 组件需要添加 `.vue` 后缀
![image](https://user-images.githubusercontent.com/36569518/173499516-1d116705-a13d-4203-86e5-d65d2be85645.png)

3. 缺失状态管理
![image](https://user-images.githubusercontent.com/36569518/173499829-3fe508b1-81f8-4de3-b2b3-95fbd0025803.png)

最后，该问题属于特定业务基础问题，并非模板本身问题。
