### ISSUE TITLE
能否添加一下pinia持久化

### ISSUE THREAD

**Issue by zhl154381001** [dishait/tov-template#29]
### nodejs 版本

TODO

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

TODO

(推荐使用 `pnpm`)

<br />

### 系统

win10

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
靓仔你好，已实现，可见 👉 [feat: 添加 pinia 的持久化](https://github.com/dishait/tov-template/commit/096ace76a87f1bf3e473159245eb347cf664559f)，具体用法可见 👉 [pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate)

**Comment by zhl154381001** [comment]
感谢大佬
| |
heling.zhang
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年7月1日 14:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [dishait/tov-template] 能否添加一下pinia持久化 (Issue #29) |

靓仔你好，已实现，可见 👉feat: 添加 pinia 的持久化，具体用法可见 👉pinia-plugin-persistedstate
