### ISSUE TITLE
UI框架代码提示问题

### ISSUE THREAD

**Issue by TBoyLi** [dishait/tov-template#35]
![image](https://user-images.githubusercontent.com/14815341/184791036-91fbc741-e7a0-4b56-9fcf-4750ecd38442.png)
![image](https://user-images.githubusercontent.com/14815341/184792005-ea27353e-a9b3-4cf9-9be6-e04242417e54.png)

代码提示问题应该怎么解决呀。只能用ui 的 vscode插件来解决吗？

**Comment by markthree** [comment]
@TBoyLi 靓仔你好，自动按需引入是按需引入组件类型的，所以做不到代码提示，可以安装对应 `ui` 的提示插件或者向插件 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 提 `issue`
