### ISSUE TITLE
组件按需引入build后发现组件没有编译

### ISSUE THREAD

**Issue by maoAmanda** [dishait/tov-template#36]
### nodejs 版本

16.16.0

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

pnpm : 7.8.0

(推荐使用 `pnpm`)

<br />

### 系统

MacOS Monterey 12.5

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

项目中引入element-pius，build打包之后发现组件没有编译；另外项目中没有components文件夹，新建src/components，发现组件也没有经过编译；
![image](https://user-images.githubusercontent.com/40196155/185052376-c1b3e52f-4dcb-49cb-8d99-b95ac0dff0d3.png)

<br />

### 预期结果

期望能正常编译。下面是本地Dev的时候，是正常的，期望build之后和Dev一致
![image](https://user-images.githubusercontent.com/40196155/185052503-3b9508ba-c476-4e91-b05f-8e2f502bfaae.png)

<br />

### 最小测试仓库

我是用你本项目作为模板直接，pnpm add element-plus 之后跑的

**Comment by markthree** [comment]
已修复，请用最新提交的版本
