### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by quanzi006** [dishait/tov-template#4]
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/50852365/155253839-8d60a7fc-d021-44ef-8361-0c2db266130c.png">

**Comment by markthree** [comment]
靓仔你好，该模板目前支持的 `node` 版本是现在的长期维护版本 `v16`，可见 👉 [node 版本推荐](https://github.com/dishait/tov-template#node-%E7%89%88%E6%9C%AC%E6%8E%A8%E8%8D%90-)。可以更新版本后重试

**Comment by quanzi006** [comment]
是的，是node版本的问题
