### ISSUE TITLE
能否升级到vite3.0

### ISSUE THREAD

**Issue by zhl154381001** [dishait/tov-template#40]
### nodejs 版本

TODO

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

TODO

(推荐使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@zhl154381001 靓仔你好，已经是 `vite3` 了

![image](https://user-images.githubusercontent.com/36569518/193204280-73b6a846-a868-4049-8822-43b400e8bfc5.png)

具体可见 → [package.json](https://github.com/dishait/tov-template/blob/main/package.json)

**Comment by zhl154381001** [comment]
OKKK


| |
heling.zhang
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月30日 14:25 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [dishait/tov-template] 能否升级到vite3.0 (Issue #40) |

@zhl154381001 靓仔你好，已经是 vite3 了

具体可见 → package.json
