### ISSUE TITLE
使用iconfont的symbol引入方式时，无法打包

### ISSUE THREAD

**Issue by zhl154381001** [dishait/tov-template#41]
### nodejs 版本

TODO

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

TODO

(推荐使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@zhl154381001 靓仔你好，请提供最小复现库

**Comment by markthree** [comment]
@靓仔你好，很抱歉，未提供复现库将关闭该 `issue`
