### ISSUE TITLE
出现@click的Typescript的格式检查错误

### ISSUE THREAD

**Issue by Chonz-dot** [dishait/tov-template#42]
### nodejs 版本

(推荐使用 `v16` 以上)
v17.2.0
<br />

### 包管理器及其版本 
pnpm

(推荐使用 `pnpm`)

<br />

### 系统
mac

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

将代码从git上拉下来，使用pnpm安装完依赖之后发现@click的类型提示错误。之前接触的其他vue3+ts项目没有出现这种提示，谷歌了没能查询到解决办法（typescript萌新）

<img width="780" alt="image" src="https://user-images.githubusercontent.com/65055774/195544316-f61aeb32-3ca7-4bbd-8de7-dee09fdcdead.png">

<br />

### 预期结果
不使用tsignore也能够通过检查

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@Chonz-dot 靓仔你好，需要用 `back()` 而不是 `back`

**Comment by Chonz-dot** [comment]
给这个问题卡了两天，找到解决办法了
主要是vue 3.2.40和@types/node的版本问题
https://stackoverflow.com/a/74070280/20246478
