### ISSUE TITLE
tsx文件不能被自動按需導入

### ISSUE THREAD

**Issue by mngogo** [dishait/tov-template#43]
手動import  tsx文件，不認。去掉.tsx尾，可以正常顯示。但是無法按需自動識別導入tsx 組件。 
src/componets/XXX.tsx

**Comment by markthree** [comment]
@mngogo 靓仔你好，已修复，具体变动可见 👉 [fix: 修复 tsx 组件不识别](https://github.com/dishait/tov-template/commit/f5c4bc52fadc03cef97ce83dfe675eb1de04ea61)
