### ISSUE TITLE
icon不能動態加載？

### ISSUE THREAD

**Issue by mngogo** [dishait/tov-template#44]
icon 自動按需加載，能否優化，自動按需動態加載？
例如：<i-mdi:{var} />  ??

**Comment by markthree** [comment]
@mngogo 靓仔你好，目前不支持该特性，欢迎 `pr`。`icon` 目前由该插件提供支持 👉 [unplugin-icons](https://github.com/antfu/unplugin-icons)，可以看看是否为你提供实现思路。

**Comment by mngogo** [comment]
能力不足啊。看了插件，感覺不如徹底自己重寫還簡單點。他這個就沒邏輯可下手啊。直接使用模板替換的方式測了一晚，還是差點。 回頭有思路了，來PR吧。

**Comment by mngogo** [comment]
折騰了2天。插件試試換個：vite-plugin-purge-icons， 你這模板就完美了

**Comment by mngogo** [comment]
hi，經過驗證測試，vite-plugin-purge-icons確實可以實現動態按需加載， 嘗試PR了一天，沒成功。可能網絡卡，也和我本人初次使用不會有關。你後面遇到需要的時候，可以更新。當然不介意指導我PR的話，歡迎聯係老聃科技，vx: Monatech ：）
另：參考 viteses <div i=“`mdi:${var”}`" />亦可支持。

**Comment by markthree** [comment]
@mngogo 靓仔你好，该功能已支持，具体可见 👉 [dishait/tov-template#8-%E5%](https://github.com/dishait/tov-template#8-%E5%9B%BE%E6%A0%87%E8%87%AA%E5%8A%A8%E5%BC%95%E5%85%A5)

**Comment by mngogo** [comment]
感謝，你的工作很棒，幫了我很大的忙。謝謝你的分享。
歡迎關注老聃科技公衆號，協作共創仙世。
----- 原始邮件 -----
发件人：markthree ***@***.***>
收件人：dishait/tov-template ***@***.***>
抄送人：Mona ***@***.***>,  Mention ***@***.***>
主题：Re:_[dishait/tov-template]_icon不能動態加載？_(Issue_#44)
日期：2023年05月19日 19点24分


@mngogo 靓仔你好，该功能已支持，具体可见 👉 dishait/tov-template#8-%E5%
