### ISSUE TITLE
是否考虑出一个vite+react模板

### ISSUE THREAD

**Issue by zhl154381001** [dishait/tov-template#48]
### nodejs 版本

TODO

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

TODO

(推荐使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@zhl154381001 靓仔你好，应该不会在出新的 `vite` 模板，因为现有模板存在这些问题 👉 https://github.com/dishait/tov-template/issues/46，不过可能会在按需方案中加入 `react`，尽情期待 🫡

**Comment by markthree** [comment]
@zhl154381001 靓仔你好，由于该模板集成了很多 `vue` 有但是 `react` 中没有的库，所以不会有 `react` 的版本。你可以使用社区中的 [vitesse-lite-react](https://github.com/lxy-yz/vitesse-lite-react)
