### ISSUE TITLE
自定义布局无效

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#49]
## 信息

使用default.vue布局没问题，当我添加登录页面时需用新的布局，但是新定义的custom.vue页面不生效，还是用的default。

**Comment by luoqiz** [comment]
![image](https://user-images.githubusercontent.com/22161059/227892987-c229f30f-aea4-4f1d-813a-8f7307d2d499.png)

**Comment by markthree** [comment]
@luoqiz  靓仔，试试👇
```html
<route lang="yaml">
    meta:
      layout: custom
</route>
```

**Comment by luoqiz** [comment]
我最开始仿照的notfound页面做的噢，完全复制过来的

**Comment by luoqiz** [comment]
对啊，大佬。因为登录页面没有做布局，只是入口即可，和notFound页面一样，所以我复用了notFound。

**Comment by markthree** [comment]
@luoqiz 靓仔你好，已确认 `bug`，排查中。

**Comment by markthree** [comment]
@luoqiz 靓仔你好，问题已修复 👉 fix: [commit/2b38697](https://github.com/dishait/vite-plugin-vue-meta-layouts/commit/2b386975dcb3dca0e4e2a60fc3150b6626f4281c)

**Comment by luoqiz** [comment]
大佬，还是不行啊。你在 default.vue 添加一些东西，如下图所示，当加载 /login的时候，default里面的东西也会显示出来，两个布局文件叠加了
![image](https://user-images.githubusercontent.com/22161059/228197042-9d4b0ac2-4d94-4971-b04e-68c1ee79d0a7.png)

**Comment by markthree** [comment]
@luoqiz 靓仔，不要碰 `default` 布局，因为所有路由都会应用上

**Comment by markthree** [comment]
@luoqiz 如果希望公用一个布局，请手动创建并声明

**Comment by markthree** [comment]
@luoqiz 就像这样 👉 [stackblitz](https://stackblitz.com/edit/github-8vodmr-mn5uuw?file=src%2Flayouts%2Fdefault.vue,src%2Flayouts%2Fdemo.vue,src%2Fpages%2Flogin.vue)

**Comment by markthree** [comment]
@luoqiz 靓仔，确实不全应用默认布局会更人性化一点，欢迎关注 👉 [issues/52](https://github.com/dishait/tov-template/issues/52)，将在最近处理。

**Comment by markthree** [comment]
@luoqiz 靓仔你好，已处理
