### ISSUE TITLE
怎么结合ElementPlus？

### ISSUE THREAD

**Issue by joyswing** [dishait/tov-template#5]
怎么结合ElementPlus？给个例子如何

**Comment by markthree** [comment]
靓仔你好，直接装 `element-plus` 即可按需使用，但目前对于组件库按需使用性能还不高，所以等下我会配置一个简单的 `element-plus` 例子。

**Comment by markthree** [comment]
靓仔你好，我开了个新的仓库，简单让 `tov-template` 和 `element-plus` 更高效的结合使用，具体可见 👉 [tov-template-with-element-plus](https://github.com/markthree/tov-template-with-element-plus)

**Comment by greenhand-xj** [comment]
大佬，问下element-plus的图标有什么简便的方式吗，在vue3中使用

**Comment by markthree** [comment]
> 大佬，问下element-plus的图标有什么简便的方式吗，在vue3中使用

可以直接引入后 `app.use`，具体用法可参考这个 👉 [tov-template-with-element-plus/src/modules/element-plus-icon](https://github.com/markthree/tov-template-with-element-plus/blob/main/src/modules/element-plus-icon.ts)

**Comment by greenhand-xj** [comment]
> > 大佬，问下element-plus的图标有什么简便的方式吗，在vue3中使用
> 
> 可以直接引入后 `app.use`，具体用法可参考这个 👉 [tov-template-with-element-plus/src/modules/element-plus-icon](https://github.com/markthree/tov-template-with-element-plus/blob/main/src/modules/element-plus-icon.ts)
谢谢
