### ISSUE TITLE
路由嵌套

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#51]
## 信息
在 layout/default.vue 中已经嵌入routerView，在page下的home/index.vue 文件中再次配置routerView 并使用vant tab组件配置to属性，此时点击就跳转到 /home/focus 路径下, 但是会丢失 /home 页面上的 tab标签栏，大佬，您知道怎么处理嘛？

![image](https://user-images.githubusercontent.com/22161059/227985088-76f1c7af-77a9-443e-91bc-0eb8f93b55a5.png)

**Comment by markthree** [comment]
@luoqiz 靓仔你好，可以创建跟目录相同名字的路由，以该路由作为根路由。
例如你有 `src/pages/login` 目录，可以新建 `src/pages/login.vue` 作为根路由。在根路由中设置 `RouteView`。

**Comment by markthree** [comment]
具体可以看这个示例 👉 [nest-route-demo](https://stackblitz.com/edit/github-8vodmr?file=src/pages/login.vue)
