### ISSUE TITLE
依赖更新 无法运行 报 require is not defined

### ISSUE THREAD

**Issue by Yacj** [dishait/tov-template#55]
### nodejs 版本

v16.14.0

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

pnpm  8.5.0

(推荐使用 `pnpm`)

<br />

### 系统

win10

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述
依赖升到最新之后  应该是 vite-plugin-mock 报 require is not defined 看了这个库的issues bug 挺多 可以考虑替换其他库
![EDK5 %MLI 5 CCDGGH}X(L2](https://github.com/dishait/tov-template/assets/11175513/4d37c352-920e-4e41-9954-a7464ae02777)
![V2J_%UD@N@OIDF2CB L3NR](https://github.com/dishait/tov-template/assets/11175513/7546782d-1e47-41be-bdf0-b4be14377bec)

<br />

### 预期结果

正常运行
<br />

### 最小测试仓库

更新最新依赖即可

**Comment by markthree** [comment]
@Yacj 靓仔你好，非模板本身问题，该 `bug` 已有 `pr` 👉 [vite-plugin-mock/pull/96](https://github.com/vbenjs/vite-plugin-mock/pull/96)，可以暂时先使用 `^2.9.8`

**Comment by Yacj** [comment]
ok 我关闭了
