### ISSUE TITLE
components目录下其他文件夹的组件引入失效

### ISSUE THREAD

**Issue by ottocsb** [dishait/tov-template#57]
### nodejs 版本

18.12

<br />

### 包管理器及其版本 

pnpm

<br />

### 描述

![image](https://github.com/dishait/tov-template/assets/83228451/9cd41ddd-a66f-4f1c-abd9-82a90c6f5811)
components目录下其他文件夹的组件引入失效，个人项目使用此模板搭建，刚刚pull了一下，发现原来生效的突然失效了，把此项目最新代码拉下来发现也是失效的

<br />

### 预期结果

正常引用组件

<br />

### 最小测试仓库

此仓库

**Comment by markthree** [comment]
@ottocsb 靓仔你好，我在最近规范了内嵌组件。如果你是旧项目。可以在 `presets/index.ts` 里把 `directoryAsNamespace` 改为 `false` 。

**Comment by ottocsb** [comment]
感谢回复，按照你的方法，没有引用`icones`图标的页面可以加载了，个人项目部分页面引用`icones`的图标加载失败，我在此项目内也做了尝试，也是加载失败，网页会无法进入， 如下图
![image](https://github.com/dishait/tov-template/assets/83228451/429f01f4-6fc5-4097-bfe5-4b1f1172f3dc)
![image](https://github.com/dishait/tov-template/assets/83228451/717ad9cb-6b16-409d-8387-633b53b80786)

**Comment by markthree** [comment]
@ottocsb 靓仔你好，图标组件目前测试已经失效，后边会改为 unocss 图标方案 👉 [Icons preset](https://unocss.dev/presets/icons#icon-collection-customization)

**Comment by markthree** [comment]
@ottocsb 靓仔你好，图标使用方式已更新，具体可见 👉 [dishait/tov-template#8-%E5%](https://github.com/dishait/tov-template#8-%E5%9B%BE%E6%A0%87%E8%87%AA%E5%8A%A8%E5%BC%95%E5%85%A5)

**Comment by markthree** [comment]
@ottocsb 关于嵌套组件的用法更新为 👉 [dishait/tov-template#7-%E](https://github.com/dishait/tov-template#7-%E7%BB%84%E4%BB%B6%E8%87%AA%E5%8A%A8%E5%BC%95%E5%85%A5)，当然你仍然可以通过在 `presets/index.ts` 里把 `directoryAsNamespace` 改为 `false` 延用旧模式
