### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by ottocsb** [dishait/tov-template#58]
### nodejs 版本

18.12.1
<br />

### 包管理器及其版本 

 `pnpm`
<br />

### 系统

 `win10`
<br />
<br />

### 描述

最新版拉取后，pnpm install后无法运行，错误如下图
![image](https://github.com/dishait/tov-template/assets/83228451/120971ad-c629-447a-b4e0-e408bd99cbb0)
<br />

### 预期结果

正常运行
<br />

### 最小测试仓库

此仓库

**Comment by ottocsb** [comment]
看起来像是vite-plugin-use-modules新版本的问题

**Comment by ottocsb** [comment]
![image](https://github.com/dishait/tov-template/assets/83228451/5bd23246-b05a-4c23-bb3a-3caffc450b9a)
dist生产的三个文件都是 import jiti from "file:///D:/code/work/vite-plugin-use-modules/node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/lib/index.js";
使用了你构建的目录的位置？

**Comment by markthree** [comment]
@ottocsb 靓仔你好，可以更新 `vite-plugin-use-modules` 为 `v1.4.2`，该问题已修复。模板里的已经更新了

**Comment by ottocsb** [comment]
dalao，拉取最新版后升级依赖，报错依旧，删除依赖重新pnpm i 还是无法启动

**Comment by markthree** [comment]
@ottocsb 靓仔，再试试将 `vite-plugin-use-modules` 为 `v1.4.3` 看看，我又更了一个版本
