### ISSUE TITLE
你好，请问如何将naive ui 暗黑模式与tov template 匹配

### ISSUE THREAD

**Issue by iyuangang** [dishait/tov-template#6]
https://github.com/iyuangang/tov-template
演示代码在如上链接，naive ui 暗黑模式的切换与tov template 是分离的，如果弃用tov template 的切换效果，后续跟进升级可能改动会比较大。
请问大佬如何使两个模式匹配，不影响后续同步tov template 升级。

**Comment by markthree** [comment]
靓仔，我开了个仓库。让 `tov-template` 与 `naive-ui` 更好的结合。具体可见 [tov-template-with-naive-ui](https://github.com/markthree/tov-template-with-naive-ui)。

暗黑模式的结合方式可见 👉 [tov-template-with-naive-ui/src/App.vue](https://github.com/markthree/tov-template-with-naive-ui/blob/main/src/App.vue)

**Comment by iyuangang** [comment]
> 靓仔，我开了个仓库。让 `tov-template` 与 `naive-ui` 更好的结合。具体可见 [tov-template-with-naive-ui](https://github.com/markthree/tov-template-with-naive-ui)。
> 
> 暗黑模式的结合方式可见 👉 [tov-template-with-naive-ui/src/App.vue](https://github.com/markthree/tov-template-with-naive-ui/blob/main/src/App.vue)

学习了，大佬神速

**Comment by markthree** [comment]
> > 靓仔，我开了个仓库。让 `tov-template` 与 `naive-ui` 更好的结合。具体可见 [tov-template-with-naive-ui](https://github.com/markthree/tov-template-with-naive-ui)。
> > 暗黑模式的结合方式可见 👉 [tov-template-with-naive-ui/src/App.vue](https://github.com/markthree/tov-template-with-naive-ui/blob/main/src/App.vue)
> 
> 学习了，大佬神速

不过这只是一个示例，后边更新仍然会重点放在 `tov-template` 本身😂
