### ISSUE TITLE
打包时vant组件不能正确被按需打包进去

### ISSUE THREAD

**Issue by zhl154381001** [dishait/tov-template#65]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本 

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@zhl154381001 靓仔你好，请拉取最新源码进行测试，未复现你所说的问题
