### ISSUE TITLE
i18n多语言例子

### ISSUE THREAD

**Issue by joyswing** [dishait/tov-template#7]
现有的例子多语言文件比较简单，实际翻译文件应该是多层嵌套的，如果可以能否进一步举例子？

**Comment by markthree** [comment]
靓仔你好，已提供嵌套例子，具体可见最新提交的 [locales](https://github.com/dishait/tov-template/tree/main/locales) 与 [Index.vue](https://github.com/dishait/tov-template/blob/main/src/pages/Index.vue)

**Comment by markthree** [comment]
更具体的使用，可见 [i18n文档](https://vue-i18n.intlify.dev/)以及阮一峰先生的 [YAML 语言教程](http://ruanyifeng.com/blog/2016/07/yaml.html)
