### ISSUE TITLE
component 动态组件失效

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#80]
## 信息
我在使用component动态组件封装form，使用的是element-plus，动态指定item类型的时候，无法显示。

### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本 

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by luoqiz** [comment]
以下是代码
`<script setup lang="ts">
import { isArray } from "@/utils/is";
import { ElForm } from "element-plus";

const types: Record<string, string> = {
  input: "el-input",
  select: "el-select",
  inputNumber: "el-input-number",
  timePicker: "el-time-picker",
  datePicker: "el-date-picker",
  richText: "WangEditor"
};

const inputTypes = ["el-input", "el-input-number", "async-select"];

type CFormChildOptions = Omit<CFormOptions, "rules" | "children">;

type CFormOptions = {
  label: string;
  name: string;
  type?: string;
  tagName?: string;
  props?: any;
  rules?: any;
  scopedSlot?: string;
  itemExtra?: any;
  colSpan?: any; // 参照 ElCol 的 属性
  hidden?: boolean;
  on?: any;
  children?: CFormChildOptions[];
};

interface CFormProps {
  options: CFormOptions[];
  gutter?: number;
  colSpan?: { span: number };
  value: any;
  loading?: boolean;
}

const props = withDefaults(defineProps<CFormProps>(), {
  options: () => [],
  gutter: 24,
  value: {},
  loading: false
});

const emits = defineEmits(["submit", "update:value"]);
const formRef = ref<InstanceType<typeof ElForm>>();
const validatorRules = ref({});
const formData = ref<CFormOptions[]>([]);
const modelProps = ref<any>({});

const filterChildrenOption = (children: any[]) => {
  return children.map((item) => {
    let { name, type, tagName, ...rest } = item;

    if (types[type] && !tagName) {
      tagName = types[type];
    }
    return {
      ...rest,
      name,
      tagName
    };
  });
};

watch(
  () => props.options,
  (val) => {
    const validatorRulesObj: any = {};
    formData.value = val.map((item) => {
      let { name, type, children, rules, tagName, ...rest } = item;

      if (rules) {
        validatorRulesObj[name] = rules;
      }
      if (type && types[type] && !tagName) {
        tagName = types[type];
      }
      if (children && isArray(children)) {
        children = filterChildrenOption(children);
      }

      return {
        ...rest,
        name,
        tagName,
        children
      };
    });
    validatorRules.value = validatorRulesObj;
  },
  { immediate: true }
);

const computedColSpan = computed(() => {
  const defaultColSpan =
    props.options && props.options.length > 10 ? { md: 12, xs: 24 } : { span: 24 };
  return props.colSpan || defaultColSpan;
});

async function submit() {
  await formRef.value?.validate((valid: boolean) => {
    if (valid) {
      const values = props.value;
      emits("submit", values);
    }
  });
}

function validateField(...args: any[]) {
  formRef.value?.validateField(...args);
}
function validate(...args: any[]) {
  formRef.value?.validate(...args);
}
function resetFields(...args: any[]) {
  formRef.value?.resetFields(...args);
}
function clearValidate(...args: any[]) {
  formRef.value?.clearValidate(...args);
}
defineExpose({
  validateField,
  validate,
  resetFields,
  clearValidate,
  submit
});

watch(
  () => props.value,
  (val: any) => {
    modelProps.value = val;
  },
  { immediate: true }
);

watchEffect(() => {
  emits("update:value", modelProps.value);
});
</script>

<template>
  <div v-loading="loading">
    <el-form ref="formRef" :rules="validatorRules" :model="value" v-bind="$attrs">
      <el-row :gutter="gutter">
        <template v-for="(item, index) in formData" :key="index">
          <el-col v-if="!item.hidden" v-bind="item.colSpan || computedColSpan" :key="item.name">
            <el-form-item :prop="item.name" :label="item.label" v-bind="item.itemExtra">
              <template v-if="item.scopedSlot && $slots[item.scopedSlot]">
                <slot :name="item.scopedSlot" :value="value" :option="item" />
              </template>
              <template v-else-if="item.tagName">
                <template v-if="inputTypes.includes(item.tagName)">
                  <component
                    :is="item.tagName"
                    v-model.trim="modelProps[item.name]"
                    v-bind="item.props"
                    v-on="item.on ?? {}"
                  />
                </template>
                <template v-else-if="item.children">
                  <component
                    :is="item.tagName"
                    v-model.trim="modelProps[item.name]"
                    v-bind="item.props"
                    v-on="item.on ?? {}"
                  >
                    <template v-for="(child, cIndex) in item.children" :key="cIndex">
                      <component :is="child.tagName" v-bind="child.props" v-on="child.on ?? {}" />
                    </template>
                  </component>
                </template>
                <template v-else>
                  <component
                    :is="item.tagName"
                    v-model="modelProps[item.name]"
                    v-bind="item.props"
                    v-on="item.on ?? {}"
                  />
                </template>
              </template>
            </el-form-item>
          </el-col>
        </template>
      </el-row>
    </el-form>
  </div>
</template>

<style scoped></style>
`

**Comment by luoqiz** [comment]
使用案例
```
<script setup lang="ts">
import { FormInstance } from 'element-plus'
import { ArticleModel } from '~/model/article'

const { t } = useI18n()

const htmlStr = ref('<p>wangEditor二次封装</p>')
const options = computed(() => {
	return [
		{
			name: 'title',
			type: 'input',
			label: t('page.common.design.article.form.title'),
			rules: [
				{
					required: true,
					message: t('page.common.design.article.form.title_placeholder'),
					trigger: 'blur',
				},
			],
			props: {
				maxLength: 50,
				placeholder: t('page.common.design.article.form.title_placeholder'),
			},
		},
		{
			name: 'content',
			type: 'input',
			label: t('page.common.design.article.form.content'),
			rules: [
				{
					required: true,
					message: t('page.common.design.article.form.content_placeholder'),
					trigger: 'blur',
				},
			],
			props: {
				autosize: { minRows: 4, maxRows: 8 },
				type: 'textarea',
				placeholder: t('page.common.design.article.form.content_placeholder'),
			},
		},
		{
			name: 'type',
			label: t('page.common.design.article.form.type'),
			rules: [
				{
					required: true,
					message: t('page.common.design.article.form.type_placeholder'),
					trigger: 'blur',
				},
			],
			scopedSlot: 'type',
		},
	]
})

const model = ref<Partial<ArticleModel>>({})
const ruleFormRef = ref<FormInstance>()
const visible = ref(false)
</script>

<template>
	<kite-form
		ref="ruleFormRef"
		v-model:value="model"
		label-width="150px"
		:options="options"
	>
		<template #type>
			<el-radio-group v-model="model.type" class="ml-4">
				<el-radio label="history" size="large">历史</el-radio>
				<el-radio label="literature" size="large">文学</el-radio>
				<el-radio label="technology" size="large">科技</el-radio>
			</el-radio-group>
		</template>
	</kite-form>

	<br />
	<hr />
	<ElButton @click="visible = !visible"> 显示</ElButton>
	<WangEditor v-model="htmlStr" />
	<br />
	<hr />
	<p>输入的结果：</p>
	{{ htmlStr }}
</template>

<style></style>
```

**Comment by markthree** [comment]
@luoqiz 靓仔你好，[unplugin-vue-component](https://github.com/antfu/unplugin-vue-components) 并不支持动态 `component`。具体可见 👉 [unplugin-vue-components/issues/643#issuecomment-1588951920](https://github.com/antfu/unplugin-vue-components/issues/643#issuecomment-1588951920) 讨论

**Comment by markthree** [comment]
> 以下是代码
> 
> ```
> <script setup lang="ts">
> import { isArray } from "@/utils/is";
> import { ElForm } from "element-plus";
> 
...
> ```

我认为这个示例，应该先手动引入 `element-plus` 的组件

```html
<script setup lang="ts">
import { ElForm } from "element-plus"
</script>
```

**Comment by luoqiz** [comment]
可以了，另外一个问题，如何手动注册我自己的组件？

**Comment by luoqiz** [comment]
可以了，多谢
