### ISSUE TITLE
多语言翻译如果想用json文件不是yml文件该怎么办？

### ISSUE THREAD

**Issue by 1185497683** [dishait/tov-template#86]
### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本 

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@1185497683 靓仔你好，在 `src/plugins/i18n.ts` 中更改 `yaml` 为 `json` 即可
```diff
// src/plugins/i18n.ts
const messages = Object.fromEntries(
	Object.entries(
+		import.meta.glob('../../locales/*.json', {
			eager: true,
		}),
	).map(([key, value]) => {
+		const yaml = key.endsWith('.json')
		// @ts-ignore
		return [key.slice(14, yaml ? -5 : -4), value.default]
	}),
)
```
之后就可以在 `locales` 中创建的 `.json` 多语言文件将会被读取到

**Comment by markthree** [comment]
@1185497683 靓仔，这是一个例子，可以在浏览器中运行查看 👉 [stackblitz.com/edit/github-zdtp19](https://stackblitz.com/edit/github-zdtp19)

**Comment by 1185497683** [comment]
回答很详细，感谢作者
