### ISSUE TITLE
部署到阿里云oss后页面丢失

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#89]
## 信息

我将项目部署到阿里云的oss上，访问正常，一旦刷新就会出问题找不到页面，另外一个项目使用#的路径没有问题。你有好的解决方案吗？
![image](https://github.com/dishait/tov-template/assets/22161059/9ab42b8b-6a2a-48f0-99a1-866ffe324a01)

### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本 

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@luoqiz 靓仔你好，这是 `router` 模式与 `oss` 服务的冲突，你可以将其改为 [hash](https://router.vuejs.org/zh/guide/essentials/history-mode.html#hash-%E6%A8%A1%E5%BC%8F) 模式，或者对 `oss` 服务进行配置 (如果可以的话)，具体配置参考可见 👉 [服务器配置示例](https://router.vuejs.org/zh/guide/essentials/history-mode.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B)

**Comment by luoqiz** [comment]
嗯，我知道原因，目前是改成hash模式的，oss没有办法配置，所以看看从前端有没有控制方案，因为我不太想带有一个#号。

**Comment by markthree** [comment]
> 嗯，我知道原因，目前是改成hash模式的，oss没有办法配置，所以看看从前端有没有控制方案，因为我不太想带有一个#号。
