### ISSUE TITLE
路由守卫示例

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#92]
## 信息

能否添加一个全局路由和单独的路由守卫示例？

### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本 

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@luoqiz 靓仔，你可以看下这个 issue #8

**Comment by luoqiz** [comment]
全局的路由守卫我写好了，但是只针对某个路由做的独享的路由守卫不知道怎么写.

**Comment by markthree** [comment]
@luoqiz 靓仔，可以用组合式 `api`，这是官网的例子 → [导航守卫](https://router.vuejs.org/zh/guide/advanced/composition-api.html#%E5%AF%BC%E8%88%AA%E5%AE%88%E5%8D%AB)

**Comment by luoqiz** [comment]
好的，多谢.
