### ISSUE TITLE
使用element-plus还是需要手动配置按需加载

### ISSUE THREAD

**Issue by joyswing** [dishait/tov-template#93]
### nodejs 版本
nodejs版本v18.16.1

执行命令pnpm install element-plus

本来期望按需加载，例如页面显示一个button，但是样式不对，于是我手动添加了

import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

export default defineConfig({
	plugins: [
		Tov(),
		Components(),
		AutoImport({
			resolvers: [ElementPlusResolver()],
		}),
		Components({
			resolvers: [ElementPlusResolver()],
		}),
	],
})

然后页面的按钮才正常显示样式，但是看你的视频用navui却不需要配置，不知道是什么原因？

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本 

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by joyswing** [comment]
我重新下载模板，执行安装命令pnpm install element-plus，没有做任何其它配置，然后可以正常显示elementplus 按钮样式了，我想之前是不是因为pnpm run dev编译运行过程中，我强行中断过导致的？如果是这个原因该怎么办？

**Comment by markthree** [comment]
@joyswing 靓仔，不需要手动配置，但是你得 `ctrl+c` 断开服务，装完 `element-plus` 后重新 `pnpm run dev`

**Comment by joyswing** [comment]
谢谢，碰到新问题再请教你，感觉你这个模板非常人性化，希望一直坚持下去。。。点赞！！！
