### ISSUE TITLE
<script setup> 支持js和ts

### ISSUE THREAD

**Issue by joyswing** [dishait/tov-template#94]
Vue文件里的<script setup> 默认应该是js脚本，但是强行提示必须<script setup lang="ts">，如果想使用js该怎么办？

**Comment by markthree** [comment]
@joyswing 靓仔，在该模板中只允许 `ts`，因为定位就是 `ts`，所以不考虑使用 `js` 的情况

**Comment by joyswing** [comment]
有的时候如果需要调用js的库，该怎么办？

**Comment by markthree** [comment]
@joyswing 可以用 `// @ts-ignore` 来忽略
```html
<script setup lang="ts">
// @ts-ignore
import mayBeJs from "jsLib"
</script>
```
