### ISSUE TITLE
框架支持ts同时也支持js

### ISSUE THREAD

**Issue by joyswing** [dishait/tov-template#96]
我觉得你这个模板框架很好，我想vue3同时支持js和ts，你这个框架能否也出一个 `js` 版本，因为ts和js本来就有争议的，不能说谁取代谁，你说呢？js用起来非常便捷

**Comment by markthree** [comment]
@joyswing 靓仔，因为 `tov-template` 的定位就是 `ts` 模板，所以一开始就是全 `ts` 的，如果现在要在其中混入对 `js` 的支持，会使得项目本身混乱且不可维护。所以当前项目不会支持 `js`。

至于另外的 `js` 版本应该也不会有，因为按需引入没有 `ts` 的类型提示对团队来说，出现 `bug` 的几率会更高。

**Comment by joyswing** [comment]
了解了，谢谢你的回答和支持！另外问一下，dishaxy.dishait.cn官网能不能出一个简单教程结合这个模板应用的教程，我看有一个结合element-plus的是js的

**Comment by markthree** [comment]
@joyswing 暂时不会对该模板出实战课程
