### ISSUE TITLE
http请求失败后重新发送

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#97]
## 信息

目前情况： 目前使用的axios发送请求，每次在发送的时候都会带上token，但是token半小时就需要刷新一次，在返回code码是token失效（例如403）的时候能够自动刷新token并重新发送一次请求。目前token是保存到cookie中。
期望： 在此项目中给出此功能的实现，统一在此框架中。

### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@luoqiz 靓仔，`token` 在不同的团队中拥有不同的规范，有的会存 `cookie` 然后传也是 `cookie`。
有的会存 `localStorage`，然后直接传 `token` 到 `http` 请求头中 `token: ${tokenValue}`,
更规范一点的会存  `localStorage`，然后传 `token` 到 `http` 请求头 `Authorization: bearer ${tokenValue}` 中。

所以很难去统一

**Comment by luoqiz** [comment]
对，可以考虑一下配置项，我在其他模板项目中看到过这种设计方案。

**Comment by markthree** [comment]
> 对，可以考虑一下配置项，我在其他模板项目中看到过这种设计方案。

靓仔，目前我暂时没有想到相关的非侵入式方案，等待其他人的补充，如果你在这方面有经验，也欢迎 `pr` 🥰

**Comment by luoqiz** [comment]
我也没有特别好的方案哈
