### ISSUE TITLE
自定义组件名称

### ISSUE THREAD

**Issue by luoqiz** [dishait/tov-template#99]
## 信息
 参考 vite-plugin-vue-setup-extend

### nodejs 版本

TODO

(推荐使用 `v18` 以上)

<br />

### 包管理器及其版本

TODO

(请使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@luoqiz 靓仔，我们可以这样做
```html
<script setup lang="ts">
defineOptions({
 name: "foo"
})
</script>
```
具体可见 👉 [defineoptions](https://cn.vuejs.org/api/sfc-script-setup.html#defineoptions)
